/* empty css                      */import{S as d}from"./assets/vendor-YE1i_CEl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();lucide.createIcons();const m=document.querySelector(".header__burger"),u=document.querySelector(".header__nav"),g=document.querySelectorAll(".header__list a"),f=()=>{u.classList.toggle("header__nav--active");const n=m.querySelector("i");u.classList.contains("header__nav--active")?n.setAttribute("data-lucide","x"):n.setAttribute("data-lucide","menu"),lucide.createIcons()};m.addEventListener("click",f);g.forEach(n=>{n.addEventListener("click",t=>{window.innerWidth<=992&&f()})});document.addEventListener("DOMContentLoaded",()=>{const n=document.getElementById("animated-code"),t=String.raw`
class NeuralXen {
  constructor(courseId) {
    this.course = courseId;
    this.status = 'Ready';
  }

  async startLearning() {
    this.status = 'Processing...';
    await new Promise(r => setTimeout(r, 1500));
    console.log("SUCCESS: Открыты новые возможности!");
    this.status = 'Complete';
  }
}

const student = new NeuralXen('FrontendMaster');
student.startLearning();
`;let o=0;anime({targets:{idx:0},idx:t.length,duration:t.length*15,easing:"linear",update(s){o=Math.floor(s.animations[0].currentValue),n.textContent=t.slice(0,o)},complete(){anime({targets:".hero__visuals",opacity:[0,1],translateX:[-50,0],duration:800,easing:"easeOutQuad"}),anime({targets:".hero__content",opacity:[0,1],translateY:[-20,0],duration:1e3,delay:200,easing:"easeOutQuad"})}}),anime({targets:".hero__title, .hero__subtitle, .hero__badge, .hero__actions",opacity:[0,1],translateY:[20,0],duration:1e3,easing:"easeOutQuad",delay:anime.stagger(150)})});typeof d<"u"?new d(".reviews-slider",{direction:"horizontal",loop:!0,slidesPerView:1,spaceBetween:30,navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},pagination:{el:".swiper-pagination",clickable:!0},breakpoints:{768:{slidesPerView:2,spaceBetween:40},1200:{slidesPerView:3,spaceBetween:50}},autoplay:{delay:5e3,disableOnInteraction:!1}}):console.error("Swiper.js не загружен. Проверьте CDN-ссылку в HTML.");const c=document.getElementById("contactForm"),h=document.getElementById("captchaQuestion"),a=document.getElementById("formMessage");let p;function l(){const n=Math.floor(Math.random()*10)+1,t=Math.floor(Math.random()*10)+1,o=["+","-"][Math.floor(Math.random()*2)];let s,e;o==="-"?n<t?(s=`${t} ${o} ${n}`,e=t-n):(s=`${n} ${o} ${t}`,e=n-t):(s=`${n} ${o} ${t}`,e=n+t),h.textContent=`Сколько будет ${s}?`,p=e}l();c&&c.addEventListener("submit",function(n){n.preventDefault();const t=document.getElementById("name").value,o=parseInt(document.getElementById("captcha").value.trim()),s=document.getElementById("consent").checked;if(a.style.display="none",o!==p){a.textContent="Ошибка: Неверный ответ на CAPTCHA. Попробуйте еще раз.",a.className="form__message error",a.style.display="block",l();return}if(!s){a.textContent="Ошибка: Вы должны согласиться с условиями использования.",a.className="form__message error",a.style.display="block";return}const e=this.querySelector(".form__submit-btn");e.textContent="Отправка...",e.disabled=!0,setTimeout(()=>{console.log(`Форма успешно отправлена: Имя - ${t}`),a.textContent=`Спасибо, ${t}! Ваша заявка принята. С вами свяжутся в течение 2 минут для начала обучения!`,a.className="form__message success",a.style.display="block",c.reset(),l(),e.textContent="Зарегистрироваться и начать",e.disabled=!1},1500)});
//# sourceMappingURL=index.js.map
