/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();lucide.createIcons();const u=document.querySelector(".header__burger"),d=document.querySelector(".header__nav"),p=document.querySelectorAll(".header__list a"),m=()=>{d.classList.toggle("header__nav--active");const n=u.querySelector("i");d.classList.contains("header__nav--active")?n.setAttribute("data-lucide","x"):n.setAttribute("data-lucide","menu"),lucide.createIcons()};u.addEventListener("click",m);p.forEach(n=>{n.addEventListener("click",t=>{window.innerWidth<=992&&m()})});document.addEventListener("DOMContentLoaded",()=>{const n=document.getElementById("animated-code"),t=String.raw`
class NeuralXen {
  constructor(courseId) {
    this.course = courseId;
    this.status = 'Ready';
  }

  async startLearning() {
    this.status = 'Processing...';
    await new Promise(r => setTimeout(r, 1500));
    console.log("SUCCESS: Открыты новые возможности!");
    this.status = 'Complete';
  }
}

const student = new NeuralXen('FrontendMaster');
student.startLearning();
`;let s=0;anime({targets:{idx:0},idx:t.length,duration:t.length*15,easing:"linear",update(o){s=Math.floor(o.animations[0].currentValue),n.textContent=t.slice(0,s)},complete(){anime({targets:".hero__visuals",opacity:[0,1],translateX:[-50,0],duration:800,easing:"easeOutQuad"}),anime({targets:".hero__content",opacity:[0,1],translateY:[-20,0],duration:1e3,delay:200,easing:"easeOutQuad"})}}),anime({targets:".hero__title, .hero__subtitle, .hero__badge, .hero__actions",opacity:[0,1],translateY:[20,0],duration:1e3,easing:"easeOutQuad",delay:anime.stagger(150)})});typeof Swiper<"u"?new Swiper(".reviews-slider",{direction:"horizontal",loop:!0,slidesPerView:1,spaceBetween:30,navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},pagination:{el:".swiper-pagination",clickable:!0},breakpoints:{768:{slidesPerView:2,spaceBetween:40},1200:{slidesPerView:3,spaceBetween:50}},autoplay:{delay:5e3,disableOnInteraction:!1}}):console.error("Swiper.js не загружен. Проверьте CDN-ссылку в HTML.");const c=document.getElementById("contactForm"),g=document.getElementById("captchaQuestion"),a=document.getElementById("formMessage");let f;function l(){const n=Math.floor(Math.random()*10)+1,t=Math.floor(Math.random()*10)+1,s=["+","-"][Math.floor(Math.random()*2)];let o,e;s==="-"?n<t?(o=`${t} ${s} ${n}`,e=t-n):(o=`${n} ${s} ${t}`,e=n-t):(o=`${n} ${s} ${t}`,e=n+t),g.textContent=`Сколько будет ${o}?`,f=e}l();c&&c.addEventListener("submit",function(n){n.preventDefault();const t=document.getElementById("name").value,s=parseInt(document.getElementById("captcha").value.trim()),o=document.getElementById("consent").checked;if(a.style.display="none",s!==f){a.textContent="Ошибка: Неверный ответ на CAPTCHA. Попробуйте еще раз.",a.className="form__message error",a.style.display="block",l();return}if(!o){a.textContent="Ошибка: Вы должны согласиться с условиями использования.",a.className="form__message error",a.style.display="block";return}const e=this.querySelector(".form__submit-btn");e.textContent="Отправка...",e.disabled=!0,setTimeout(()=>{console.log(`Форма успешно отправлена: Имя - ${t}`),a.textContent=`Спасибо, ${t}! Ваша заявка принята. С вами свяжутся в течение 2 минут для начала обучения!`,a.className="form__message success",a.style.display="block",c.reset(),l(),e.textContent="Зарегистрироваться и начать",e.disabled=!1},1500)});
//# sourceMappingURL=index.js.map
